# 构建 VitePress 网站并部署到 GitHub Pages
name: Deploy VitePress to GitHub Pages

on:
  # 当推送到 main 分支时触发
  push:
    branches: [master]
  # 允许从 Actions 选项卡手动运行工作流
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限
permissions:
  contents: read
  pages: write
  id-token: write

# 确保同时只有一个部署在运行
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 如果未启用 lastUpdated，则不需要

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0

      - name: 安装 pnpm
        run: npm install -g pnpm@10.6.3

      - name: 安装依赖
        run: pnpm install

      - name: 构建 VitePress 应用
        run: pnpm build-only

      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  # 部署工作
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
